
import __ASTRO_IMAGE_IMPORT_ZBd4wV from "@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-art-of-digital-storytelling.mdx";
import __ASTRO_IMAGE_IMPORT_Z1cBVxn from "@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-evolution-of-remote-work-technologies.mdx";
import __ASTRO_IMAGE_IMPORT_mNoGd from "@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx";
import __ASTRO_IMAGE_IMPORT_Z20PN67 from "@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-rise-of-sustainable-technology.mdx";
import __ASTRO_IMAGE_IMPORT_Zwsaan from "@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md";
import __ASTRO_IMAGE_IMPORT_1VQOkg from "@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx";
import __ASTRO_IMAGE_IMPORT_DRjl4 from "@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx";
import __ASTRO_IMAGE_IMPORT_wVqE8 from "@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fai-and-human-creativity.mdx";
import __ASTRO_IMAGE_IMPORT_ZJ33Jg from "@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx";
export default new Map([["@assets/images/blog/digital-storytelling.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-art-of-digital-storytelling.mdx", __ASTRO_IMAGE_IMPORT_ZBd4wV], ["@assets/images/blog/remote-work-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-evolution-of-remote-work-technologies.mdx", __ASTRO_IMAGE_IMPORT_Z1cBVxn], ["@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx", __ASTRO_IMAGE_IMPORT_mNoGd], ["@assets/images/blog/sustainable-tech.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fthe-rise-of-sustainable-technology.mdx", __ASTRO_IMAGE_IMPORT_Z20PN67], ["@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md", __ASTRO_IMAGE_IMPORT_Zwsaan], ["@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx", __ASTRO_IMAGE_IMPORT_1VQOkg], ["@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx", __ASTRO_IMAGE_IMPORT_DRjl4], ["@assets/images/blog/ai-creativity.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fai-and-human-creativity.mdx", __ASTRO_IMAGE_IMPORT_wVqE8], ["@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx", __ASTRO_IMAGE_IMPORT_ZJ33Jg]]);
		