name: Assertions and static report

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    PRIVJS_TOKEN: ${{ secrets.PRIVJS_TOKEN }}

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Install Global dependencies
              run: bun install -g vercel @unlighthouse/cli puppeteer

            - name: Unlighthouse assertions and client
              run: unlighthouse-ci --no-exit-code

            - name: Setup Vercel project config
              run: |
                  mkdir -p .unlighthouse/.vercel
                  echo '{"orgId":"${{ secrets.VERCEL_ORG_ID }}","projectId":"${{ secrets.VERCEL_PROJECT_ID }}"}' > .unlighthouse/.vercel/project.json
              shell: bash

            - name: Deploy reports to Vercel
              run: |
                  cd .unlighthouse
                  vercel --prod --yes --token "$VERCEL_TOKEN"
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
